// This file will be auto-generated by Supabase CLI
// For now, we'll define the types manually based on our schema

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export interface Database {
  public: {
    Tables: {
      users: {
        Row: {
          id: string
          role: 'athlete' | 'coach' | 'admin'
          created_at: string
          updated_at: string
        }
        Insert: {
          id: string
          role: 'athlete' | 'coach' | 'admin'
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          role?: 'athlete' | 'coach' | 'admin'
          created_at?: string
          updated_at?: string
        }
      }
      athlete_profiles: {
        Row: {
          id: string
          user_id: string
          first_name: string | null
          last_name: string | null
          sport: string | null
          positions: string[] | null
          grad_year: number | null
          city: string | null
          state: string | null
          bio: string | null
          gpa: number | null
          sat_score: number | null
          act_score: number | null
          height_feet: number | null
          height_inches: number | null
          weight: number | null
          profile_completeness: number
          is_public: boolean
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          user_id: string
          first_name?: string | null
          last_name?: string | null
          sport?: string | null
          positions?: string[] | null
          grad_year?: number | null
          city?: string | null
          state?: string | null
          bio?: string | null
          gpa?: number | null
          sat_score?: number | null
          act_score?: number | null
          height_feet?: number | null
          height_inches?: number | null
          weight?: number | null
          profile_completeness?: number
          is_public?: boolean
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          user_id?: string
          first_name?: string | null
          last_name?: string | null
          sport?: string | null
          positions?: string[] | null
          grad_year?: number | null
          city?: string | null
          state?: string | null
          bio?: string | null
          gpa?: number | null
          sat_score?: number | null
          act_score?: number | null
          height_feet?: number | null
          height_inches?: number | null
          weight?: number | null
          profile_completeness?: number
          is_public?: boolean
          created_at?: string
          updated_at?: string
        }
      }
      coach_profiles: {
        Row: {
          id: string
          user_id: string
          school: string | null
          school_id: string | null
          title: string | null
          sports: string[] | null
          verification_status: 'pending' | 'verified' | 'rejected'
          verification_notes: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          user_id: string
          school?: string | null
          school_id?: string | null
          title?: string | null
          sports?: string[] | null
          verification_status?: 'pending' | 'verified' | 'rejected'
          verification_notes?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          user_id?: string
          school?: string | null
          school_id?: string | null
          title?: string | null
          sports?: string[] | null
          verification_status?: 'pending' | 'verified' | 'rejected'
          verification_notes?: string | null
          created_at?: string
          updated_at?: string
        }
      }
      athlete_highlights: {
        Row: {
          id: string
          athlete_user_id: string
          title: string
          url: string
          created_at: string
        }
        Insert: {
          id?: string
          athlete_user_id: string
          title: string
          url: string
          created_at?: string
        }
        Update: {
          id?: string
          athlete_user_id?: string
          title?: string
          url?: string
          created_at?: string
        }
      }
      athlete_stats: {
        Row: {
          id: string
          athlete_user_id: string
          season: string
          stat_key: string
          stat_value: string
          source_type: 'self_reported' | 'source_link' | 'upload' | 'verified'
          source_url: string | null
          verification_status: 'self_reported' | 'source_provided' | 'verified'
          created_at: string
        }
        Insert: {
          id?: string
          athlete_user_id: string
          season: string
          stat_key: string
          stat_value: string
          source_type?: 'self_reported' | 'source_link' | 'upload' | 'verified'
          source_url?: string | null
          verification_status?: 'self_reported' | 'source_provided' | 'verified'
          created_at?: string
        }
        Update: {
          id?: string
          athlete_user_id?: string
          season?: string
          stat_key?: string
          stat_value?: string
          source_type?: 'self_reported' | 'source_link' | 'upload' | 'verified'
          source_url?: string | null
          verification_status?: 'self_reported' | 'source_provided' | 'verified'
          created_at?: string
        }
      }
      saved_athletes: {
        Row: {
          id: string
          coach_user_id: string
          athlete_user_id: string
          created_at: string
        }
        Insert: {
          id?: string
          coach_user_id: string
          athlete_user_id: string
          created_at?: string
        }
        Update: {
          id?: string
          coach_user_id?: string
          athlete_user_id?: string
          created_at?: string
        }
      }
      contact_requests: {
        Row: {
          id: string
          coach_user_id: string
          athlete_user_id: string
          status: 'pending' | 'approved' | 'rejected'
          message: string | null
          created_at: string
        }
        Insert: {
          id?: string
          coach_user_id: string
          athlete_user_id: string
          status?: 'pending' | 'approved' | 'rejected'
          message?: string | null
          created_at?: string
        }
        Update: {
          id?: string
          coach_user_id?: string
          athlete_user_id?: string
          status?: 'pending' | 'approved' | 'rejected'
          message?: string | null
          created_at?: string
        }
      }
      discussions_threads: {
        Row: {
          id: string
          created_by: string
          title: string
          created_at: string
          is_hidden: boolean
        }
        Insert: {
          id?: string
          created_by: string
          title: string
          created_at?: string
          is_hidden?: boolean
        }
        Update: {
          id?: string
          created_by?: string
          title?: string
          created_at?: string
          is_hidden?: boolean
        }
      }
      discussions_posts: {
        Row: {
          id: string
          thread_id: string
          created_by: string
          body: string
          created_at: string
          is_hidden: boolean
        }
        Insert: {
          id?: string
          thread_id: string
          created_by: string
          body: string
          created_at?: string
          is_hidden?: boolean
        }
        Update: {
          id?: string
          thread_id?: string
          created_by?: string
          body?: string
          created_at?: string
          is_hidden?: boolean
        }
      }
      reports: {
        Row: {
          id: string
          reporter_id: string
          target_type: 'post' | 'thread' | 'user' | 'profile'
          target_id: string
          reason: string
          status: 'pending' | 'reviewed' | 'resolved'
          created_at: string
        }
        Insert: {
          id?: string
          reporter_id: string
          target_type: 'post' | 'thread' | 'user' | 'profile'
          target_id: string
          reason: string
          status?: 'pending' | 'reviewed' | 'resolved'
          created_at?: string
        }
        Update: {
          id?: string
          reporter_id?: string
          target_type?: 'post' | 'thread' | 'user' | 'profile'
          target_id?: string
          reason?: string
          status?: 'pending' | 'reviewed' | 'resolved'
          created_at?: string
        }
      }
      schools: {
        Row: {
          id: string
          name: string
          division: string | null
          location: string | null
          logo_url: string | null
          created_at: string
        }
        Insert: {
          id?: string
          name: string
          division?: string | null
          location?: string | null
          logo_url?: string | null
          created_at?: string
        }
        Update: {
          id?: string
          name?: string
          division?: string | null
          location?: string | null
          logo_url?: string | null
          created_at?: string
        }
      }
      athlete_school_interests: {
        Row: {
          id: string
          athlete_user_id: string
          school_id: string
          interest_type: 'LIKE' | 'FOLLOW' | 'TOP_CHOICE'
          visibility: 'PUBLIC_TO_VERIFIED_COACHES' | 'PRIVATE_UNTIL_APPROVED' | 'PRIVATE'
          notes: string | null
          created_at: string
        }
        Insert: {
          id?: string
          athlete_user_id: string
          school_id: string
          interest_type?: 'LIKE' | 'FOLLOW' | 'TOP_CHOICE'
          visibility?: 'PUBLIC_TO_VERIFIED_COACHES' | 'PRIVATE_UNTIL_APPROVED' | 'PRIVATE'
          notes?: string | null
          created_at?: string
        }
        Update: {
          id?: string
          athlete_user_id?: string
          school_id?: string
          interest_type?: 'LIKE' | 'FOLLOW' | 'TOP_CHOICE'
          visibility?: 'PUBLIC_TO_VERIFIED_COACHES' | 'PRIVATE_UNTIL_APPROVED' | 'PRIVATE'
          notes?: string | null
          created_at?: string
        }
      }
      conversations: {
        Row: {
          id: string
          athlete_user_id: string
          coach_user_id: string
          initiated_by: string
          status: 'OPEN' | 'ARCHIVED' | 'BLOCKED'
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          athlete_user_id: string
          coach_user_id: string
          initiated_by: string
          status?: 'OPEN' | 'ARCHIVED' | 'BLOCKED'
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          athlete_user_id?: string
          coach_user_id?: string
          initiated_by?: string
          status?: 'OPEN' | 'ARCHIVED' | 'BLOCKED'
          created_at?: string
          updated_at?: string
        }
      }
      messages: {
        Row: {
          id: string
          conversation_id: string
          sender_user_id: string
          sender_role: 'ATHLETE' | 'COACH'
          body: string
          read_at: string | null
          created_at: string
        }
        Insert: {
          id?: string
          conversation_id: string
          sender_user_id: string
          sender_role: 'ATHLETE' | 'COACH'
          body: string
          read_at?: string | null
          created_at?: string
        }
        Update: {
          id?: string
          conversation_id?: string
          sender_user_id?: string
          sender_role?: 'ATHLETE' | 'COACH'
          body?: string
          read_at?: string | null
          created_at?: string
        }
      }
      blocks: {
        Row: {
          id: string
          blocker_user_id: string
          blocked_user_id: string
          reason: string | null
          created_at: string
        }
        Insert: {
          id?: string
          blocker_user_id: string
          blocked_user_id: string
          reason?: string | null
          created_at?: string
        }
        Update: {
          id?: string
          blocker_user_id?: string
          blocked_user_id?: string
          reason?: string | null
          created_at?: string
        }
      }
      notifications: {
        Row: {
          id: string
          user_id: string
          type: 'CONTACT_REQUEST' | 'MESSAGE' | 'SAVED_TO_SHORTLIST' | 'PROFILE_VIEWED'
          title: string
          body: string | null
          related_id: string | null
          read_at: string | null
          created_at: string
        }
        Insert: {
          id?: string
          user_id: string
          type: 'CONTACT_REQUEST' | 'MESSAGE' | 'SAVED_TO_SHORTLIST' | 'PROFILE_VIEWED'
          title: string
          body?: string | null
          related_id?: string | null
          read_at?: string | null
          created_at?: string
        }
        Update: {
          id?: string
          user_id?: string
          type?: 'CONTACT_REQUEST' | 'MESSAGE' | 'SAVED_TO_SHORTLIST' | 'PROFILE_VIEWED'
          title?: string
          body?: string | null
          related_id?: string | null
          read_at?: string | null
          created_at?: string
        }
      }
    }
  }
}
